import { notFound } from "next/navigation";

export default async function SharePage({ params }: { params: Promise<{ shareSlug: string }> }) {
  const { shareSlug } = await params;
  const api = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000/api";
  const res = await fetch(`${api}/ai/visibility-check/share/${shareSlug}`, { cache: "no-store" });
  if (!res.ok) return notFound();
  const { check } = await res.json();
  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted p-6 flex items-center justify-center">
      <div className="max-w-2xl w-full border rounded-2xl p-8 bg-white shadow-xl">
        <div className="text-xs tracking-widest text-muted-foreground">AI BUSINESS VISIBILITY</div>
        <div className="text-2xl font-black mt-1">{check.score} / 100</div>
        <div className="text-sm text-muted-foreground">AI mentions you in {check.engineResults.filter((r: any) => r.mentioned).length}/{check.queries.length * 2} customer searches. Strongest competitor: {check.competitors[0]?.name} — {check.competitors[0]?.score}/10</div>
        <div className="mt-4 text-sm">Gap {check.gap} points — Customer {check.customerReputation}/100 vs AI {check.score}/100</div>
        <div className="mt-4 text-xs">See exactly why → {process.env.NEXT_PUBLIC_APP_URL || "https://beyondvyu.com"}/c/{shareSlug}</div>
        <div className="mt-6 text-[11px] text-muted-foreground">Generated by BeyondVyu — Turn customer feedback into AI visibility. <a href="/dashboard/reputation" className="underline">Analyze my business free</a></div>
      </div>
    </div>
  );
}
