import type {
  Agent,
  Conversation,
  Customer,
  FollowUpTask,
  Message,
} from "./types"

// ---------------------------------------------------------------------------
// MOCK DATA LAYER
// This is the single source of truth for the demo. When wiring the real
// WhatsApp Cloud API + Postgres, replace the exports below with DB queries —
// the component layer reads only from these shapes.
// ---------------------------------------------------------------------------

const now = Date.now()
const minsAgo = (m: number) => new Date(now - m * 60_000).toISOString()
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString()
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString()
const inHours = (h: number) => new Date(now + h * 3_600_000).toISOString()
const inDays = (d: number) => new Date(now + d * 86_400_000).toISOString()

export const agents: Agent[] = [
  {
    id: "a1",
    name: "Priya Nair",
    email: "priya@relayhq.app",
    role: "owner",
    avatarColor: "var(--chart-1)",
    initials: "PN",
    online: true,
  },
  {
    id: "a2",
    name: "Marcus Hale",
    email: "marcus@relayhq.app",
    role: "admin",
    avatarColor: "var(--chart-2)",
    initials: "MH",
    online: true,
  },
  {
    id: "a3",
    name: "Aisha Khan",
    email: "aisha@relayhq.app",
    role: "agent",
    avatarColor: "var(--chart-3)",
    initials: "AK",
    online: false,
  },
  {
    id: "a4",
    name: "Diego Santos",
    email: "diego@relayhq.app",
    role: "agent",
    avatarColor: "var(--chart-4)",
    initials: "DS",
    online: true,
  },
]

export const currentAgent = agents[0]

export const customers: Customer[] = [
  {
    id: "c1",
    name: "Rohan Mehta",
    waId: "919820012345",
    phone: "+91 98200 12345",
    email: "rohan@brightmart.in",
    company: "BrightMart Retail",
    country: "India",
    countryCode: "IN",
    tags: ["wholesale", "repeat"],
    lifetimeValue: 184000,
    currency: "INR",
    stage: "negotiation",
    dealValue: 75000,
    ownerId: "a1",
    createdAt: daysAgo(42),
    lastContactAt: minsAgo(4),
    notes: "Prefers calls after 6pm. Sensitive to delivery timelines.",
  },
  {
    id: "c2",
    name: "Sarah Collins",
    waId: "14155550142",
    phone: "+1 415 555 0142",
    email: "sarah@northpeak.co",
    company: "NorthPeak Studio",
    country: "United States",
    countryCode: "US",
    tags: ["agency", "high-value"],
    lifetimeValue: 12400,
    currency: "USD",
    stage: "quotation",
    dealValue: 4800,
    ownerId: "a2",
    createdAt: daysAgo(11),
    lastContactAt: minsAgo(22),
    notes: "Asked for quotation on the Pro retainer.",
  },
  {
    id: "c3",
    name: "Aman Gupta",
    waId: "919810098765",
    phone: "+91 98100 98765",
    company: "Gupta Traders",
    country: "India",
    countryCode: "IN",
    tags: ["payment-pending"],
    lifetimeValue: 56000,
    currency: "INR",
    stage: "won",
    dealValue: 28000,
    ownerId: "a4",
    createdAt: daysAgo(64),
    lastContactAt: hoursAgo(3),
    notes: "Said he'd pay the balance by Friday.",
  },
  {
    id: "c4",
    name: "Emily Zhang",
    waId: "6591234567",
    phone: "+65 9123 4567",
    email: "emily@lumenlabs.sg",
    company: "Lumen Labs",
    country: "Singapore",
    countryCode: "SG",
    tags: ["new"],
    lifetimeValue: 0,
    currency: "USD",
    stage: "new",
    dealValue: 2200,
    createdAt: hoursAgo(2),
    lastContactAt: minsAgo(48),
  },
  {
    id: "c5",
    name: "Kabir Singh",
    waId: "919730011223",
    phone: "+91 97300 11223",
    company: "Singh Interiors",
    country: "India",
    countryCode: "IN",
    tags: ["interiors", "referral"],
    lifetimeValue: 320000,
    currency: "INR",
    stage: "contacted",
    dealValue: 145000,
    ownerId: "a3",
    createdAt: daysAgo(6),
    lastContactAt: hoursAgo(8),
  },
  {
    id: "c6",
    name: "Olivia Brown",
    waId: "447700900123",
    phone: "+44 7700 900123",
    email: "olivia@craftedco.uk",
    company: "Crafted & Co.",
    country: "United Kingdom",
    countryCode: "GB",
    tags: ["d2c"],
    lifetimeValue: 3400,
    currency: "USD",
    stage: "contacted",
    dealValue: 1500,
    ownerId: "a2",
    createdAt: daysAgo(3),
    lastContactAt: hoursAgo(20),
  },
  {
    id: "c7",
    name: "Vikram Patel",
    waId: "919900223344",
    phone: "+91 99002 23344",
    company: "Patel Electronics",
    country: "India",
    countryCode: "IN",
    tags: ["wholesale"],
    lifetimeValue: 98000,
    currency: "INR",
    stage: "lost",
    dealValue: 40000,
    ownerId: "a4",
    createdAt: daysAgo(30),
    lastContactAt: daysAgo(5),
    notes: "Went with a competitor on price. Re-engage next quarter.",
  },
  {
    id: "c8",
    name: "Hana Suzuki",
    waId: "819012345678",
    phone: "+81 90 1234 5678",
    email: "hana@midoritea.jp",
    company: "Midori Tea",
    country: "Japan",
    countryCode: "JP",
    tags: ["new", "import"],
    lifetimeValue: 0,
    currency: "USD",
    stage: "new",
    dealValue: 3600,
    createdAt: hoursAgo(5),
    lastContactAt: hoursAgo(5),
  },
]

export const conversations: Conversation[] = [
  {
    id: "conv1",
    customerId: "c1",
    status: "open",
    priority: "high",
    assignedTo: "a1",
    lastMessagePreview: "Can you do 70k if I order two units this week?",
    lastMessageAt: minsAgo(4),
    unread: 2,
    windowOpen: true,
    windowMinutesLeft: 1411,
    labels: ["negotiation", "wholesale"],
    viewingAgentIds: ["a1", "a2"],
  },
  {
    id: "conv2",
    customerId: "c2",
    status: "waiting",
    priority: "normal",
    assignedTo: "a2",
    lastMessagePreview: "Thanks! Sending the quotation over now.",
    lastMessageAt: minsAgo(22),
    unread: 0,
    windowOpen: true,
    windowMinutesLeft: 1380,
    labels: ["quotation"],
  },
  {
    id: "conv3",
    customerId: "c3",
    status: "follow_up",
    priority: "high",
    assignedTo: "a4",
    lastMessagePreview: "I'll transfer the balance by Friday for sure.",
    lastMessageAt: hoursAgo(3),
    unread: 0,
    windowOpen: true,
    windowMinutesLeft: 1080,
    labels: ["payment-pending"],
  },
  {
    id: "conv4",
    customerId: "c4",
    status: "open",
    priority: "normal",
    lastMessagePreview: "Hi! Do you ship to Singapore? Saw your ad.",
    lastMessageAt: minsAgo(48),
    unread: 1,
    windowOpen: true,
    windowMinutesLeft: 1392,
    labels: ["new", "unassigned"],
  },
  {
    id: "conv5",
    customerId: "c5",
    status: "open",
    priority: "normal",
    assignedTo: "a3",
    lastMessagePreview: "Could you share the catalogue for living room sets?",
    lastMessageAt: hoursAgo(8),
    unread: 0,
    windowOpen: true,
    windowMinutesLeft: 480,
    labels: ["interiors"],
  },
  {
    id: "conv6",
    customerId: "c6",
    status: "open",
    priority: "low",
    assignedTo: "a2",
    lastMessagePreview: "Got it, will review and revert tomorrow.",
    lastMessageAt: hoursAgo(20),
    unread: 0,
    windowOpen: true,
    windowMinutesLeft: 240,
    labels: ["d2c"],
  },
  {
    id: "conv7",
    customerId: "c8",
    status: "open",
    priority: "normal",
    lastMessagePreview: "Konnichiwa — interested in bulk matcha order.",
    lastMessageAt: hoursAgo(5),
    unread: 1,
    windowOpen: true,
    windowMinutesLeft: 1140,
    labels: ["new", "unassigned", "import"],
  },
  {
    id: "conv8",
    customerId: "c7",
    status: "closed",
    priority: "low",
    assignedTo: "a4",
    lastMessagePreview: "Understood, thanks for letting us know.",
    lastMessageAt: daysAgo(5),
    unread: 0,
    windowOpen: false,
    labels: ["lost"],
  },
]

export const messages: Message[] = [
  // conv1 — Rohan Mehta, active negotiation
  { id: "m1", conversationId: "conv1", direction: "inbound", type: "text", body: "Hey Priya, following up on the bulk order we discussed.", timestamp: hoursAgo(2) },
  { id: "m2", conversationId: "conv1", direction: "outbound", type: "text", authorId: "a1", status: "read", body: "Hi Rohan! Yes — for 2 units the standard price is ₹80,000 total.", timestamp: hoursAgo(2) },
  { id: "m3", conversationId: "conv1", direction: "inbound", type: "text", body: "That's a bit high for me right now.", timestamp: minsAgo(90) },
  { id: "m4", conversationId: "conv1", direction: "outbound", type: "note", authorId: "a2", body: "Heads up — he negotiated 12% off last quarter. Margin floor is ₹68k.", timestamp: minsAgo(80) },
  { id: "m5", conversationId: "conv1", direction: "inbound", type: "text", body: "Can you do 70k if I order two units this week?", timestamp: minsAgo(4) },

  // conv2 — Sarah Collins, quotation
  { id: "m6", conversationId: "conv2", direction: "inbound", type: "text", body: "Hi, can you send over the quotation for the Pro retainer?", timestamp: minsAgo(40) },
  { id: "m7", conversationId: "conv2", direction: "outbound", type: "text", authorId: "a2", status: "delivered", body: "Thanks! Sending the quotation over now.", timestamp: minsAgo(22) },
  { id: "m8", conversationId: "conv2", direction: "outbound", type: "document", authorId: "a2", status: "delivered", body: "NorthPeak — Pro Retainer Quotation.pdf", attachmentName: "quotation.pdf", timestamp: minsAgo(21) },

  // conv3 — Aman Gupta, payment follow-up
  { id: "m9", conversationId: "conv3", direction: "outbound", type: "text", authorId: "a4", status: "read", body: "Hi Aman, just a gentle reminder about the pending balance of ₹14,000.", timestamp: hoursAgo(4) },
  { id: "m10", conversationId: "conv3", direction: "inbound", type: "text", body: "I'll transfer the balance by Friday for sure.", timestamp: hoursAgo(3) },

  // conv4 — Emily Zhang, new inbound lead
  { id: "m11", conversationId: "conv4", direction: "inbound", type: "text", body: "Hi! Do you ship to Singapore? Saw your ad.", timestamp: minsAgo(48) },

  // conv5 — Kabir Singh
  { id: "m12", conversationId: "conv5", direction: "inbound", type: "text", body: "Could you share the catalogue for living room sets?", timestamp: hoursAgo(8) },

  // conv7 — Hana Suzuki
  { id: "m13", conversationId: "conv7", direction: "inbound", type: "text", body: "Konnichiwa — interested in bulk matcha order.", timestamp: hoursAgo(5) },
]

export const followUpTasks: FollowUpTask[] = [
  {
    id: "t1",
    title: "Collect ₹14,000 balance payment",
    type: "payment",
    customerId: "c3",
    conversationId: "conv3",
    assignedTo: "a4",
    dueAt: inDays(1),
    status: "pending",
    sourceQuote: "I'll transfer the balance by Friday for sure.",
  },
  {
    id: "t2",
    title: "Send revised quotation @ ₹70k",
    type: "quotation",
    customerId: "c1",
    conversationId: "conv1",
    assignedTo: "a1",
    dueAt: inHours(3),
    status: "pending",
    sourceQuote: "Can you do 70k if I order two units this week?",
  },
  {
    id: "t3",
    title: "Follow up on Pro retainer decision",
    type: "follow_up",
    customerId: "c2",
    conversationId: "conv2",
    assignedTo: "a2",
    dueAt: inDays(2),
    status: "pending",
    sourceQuote: "Sending the quotation over now.",
  },
  {
    id: "t4",
    title: "Reply to Singapore shipping enquiry",
    type: "callback",
    customerId: "c4",
    conversationId: "conv4",
    assignedTo: "a1",
    dueAt: hoursAgo(1),
    status: "overdue",
    sourceQuote: "Do you ship to Singapore?",
  },
  {
    id: "t5",
    title: "Share living room catalogue",
    type: "custom",
    customerId: "c5",
    conversationId: "conv5",
    assignedTo: "a3",
    dueAt: hoursAgo(2),
    status: "overdue",
    sourceQuote: "Could you share the catalogue for living room sets?",
  },
  {
    id: "t6",
    title: "Re-engage Patel Electronics next quarter",
    type: "follow_up",
    customerId: "c7",
    assignedTo: "a4",
    dueAt: inDays(20),
    status: "pending",
  },
]

// --- Lookup helpers (these become DB joins later) -------------------------

export const agentById = (id?: string) => agents.find((a) => a.id === id)
export const customerById = (id?: string) => customers.find((c) => c.id === id)
export const conversationById = (id?: string) =>
  conversations.find((c) => c.id === id)
export const messagesByConversation = (id: string) =>
  messages
    .filter((m) => m.conversationId === id)
    .sort((a, b) => +new Date(a.timestamp) - +new Date(b.timestamp))
